/*
归属模块：订单
关联CQ单：
脚本用途：集中受理配置地址
提交人:   郭泉宁
提交时间：20160307
发布环境：福建--集中系统地址
注意事项：
*/

-- 配置CRM2地址
-- http://134.129.126.100:9091/crm
-- http://134.132.66.44:8090/crm
delete from attr_spec where attr_id =950025979 and java_code='CRM2_URL';
INSERT INTO attr_spec (`ATTR_ID`, `ATTR_CD`, `ATTR_NAME`, `ATTR_DESC`, `ATTR_VALUE_TYPE`, `DEFAULT_VALUE`, `VALUE_FROM`, `VALUE_TO`, `IS_UNIQUE`, `IS_NULLABLE`, `STATUS_CD`, `STATUS_DATE`, `CREATE_DATE`, `CLASS_ID`, `ATTR_TYPE`, `JAVA_CODE`, `ATTR_SEQ`, `CNS_TYPE`, `REF_CLASS_ID`, `ATTR_LEVEL`, `IS_DANY_ATTR`, `IS_MULTI_VALUE`, `AREA_ID`, `REGION_CD`, `UPDATE_STAFF`, `CREATE_STAFF`, `IS_PRINT`, `ATTR_LENGTH`, `CODE_BUILDER`, `CODE_PARAM1`, `COMPLETE_FLAG`, `VISIBLE_FLAG`, `ATTR_FORMAT`, `EFFECTIVE_TYPE`, `MOD_EFF_TYPE`, `DEFAULT_TIME_PERIOD`, `EXPIRE_TYPE`, `CNS_TYPE_EXTRA`, `IS_POST`, `HB_POST`, `EXT_ATTR_NBR`, `IS_TRANS`, `REMARK`, `PRINT_EXT`, `MANAGE_GRADE`, `COMMON_REGION_ID`, `OWNER_SYSTEM`, `ATTR_SPEC_CODE_RULE`, `ATTR_SPEC_EXT_RULE`, `SELFMOD_DISVALID`, `MAINMOD_DISVALID`, `MAINDEL_DISVALID`, `MAINEXTSO_DISVALID`, `SUPEXTSO_DISVALID`, `EXT_FLAG`, `GROUP_CD`, `EXT_RULE_FLAG`, `EVENT_PROC_TYPE`, `IS_INSTANTIATION`, `EXT_ATTR_CD`, `UPDATE_DATE`) VALUES ('950025979', 'CRM2_URL', 'CRM2地址', 'CRM2地址', 'C', 'http://134.129.126.100:9091/crm', NULL, NULL, '0', '0', '1000', SYSDATE(), SYSDATE(), '-1', 'T1', 'CRM2_URL', NULL, NULL, NULL, NULL, '1', '0', '31', NULL, NULL, NULL, '1', NULL, NULL, NULL, 'Y', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10', NULL, NULL, '0', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
-- 退单下拉框主数据修改
update attr_value a set a.attr_desc=a.attr_value,a.attr_value = a.attr_value_name where a.ATTR_ID=950022696;
update attr_value b set b.attr_value_name = b.ATTR_DESC where b.ATTR_ID=950022696;