--crm端webservice配置
INSERT INTO ATTR_SPEC
  (ATTR_ID,
   ATTR_CD,
   ATTR_NAME,
   ATTR_DESC,
   ATTR_VALUE_TYPE,
   DEFAULT_VALUE,
   VALUE_FROM,
   VALUE_TO,
   IS_UNIQUE,
   IS_NULLABLE,
   STATUS_CD,
   STATUS_DATE,
   CREATE_DATE,
   CLASS_ID,
   ATTR_TYPE,
   JAVA_CODE,
   ATTR_SEQ,
   CNS_TYPE,
   REF_CLASS_ID,
   ATTR_LEVEL,
   IS_DANY_ATTR,
   IS_MULTI_VALUE,
   AREA_ID,
   REGION_CD,
   UPDATE_STAFF,
   CREATE_STAFF,
   IS_PRINT,
   ATTR_LENGTH,
   CODE_BUILDER,
   CODE_PARAM1,
   COMPLETE_FLAG,
   VISIBLE_FLAG,
   ATTR_FORMAT,
   EFFECTIVE_TYPE,
   MOD_EFF_TYPE,
   DEFAULT_TIME_PERIOD,
   EXPIRE_TYPE,
   CNS_TYPE_EXTRA,
   IS_POST,
   HB_POST,
   EXT_ATTR_NBR,
   IS_TRANS,
   REMARK,
   PRINT_EXT,
   MANAGE_GRADE,
   COMMON_REGION_ID,
   OWNER_SYSTEM,
   ATTR_SPEC_CODE_RULE,
   ATTR_SPEC_EXT_RULE,
   SELFMOD_DISVALID,
   MAINMOD_DISVALID,
   MAINDEL_DISVALID,
   MAINEXTSO_DISVALID,
   SUPEXTSO_DISVALID,
   EXT_FLAG,
   GROUP_CD,
   EXT_RULE_FLAG,
   EVENT_PROC_TYPE,
   IS_INSTANTIATION,
   EXT_ATTR_CD,
   UPDATE_DATE)
VALUES
  (-950012806,
   'CRM_WS_URL',
   'crm端weebservices地址ַ',
   'crm端weebservices地址ַ',
   'C',
   'http://134.129.126.134:9001/webapp/services/CasService',
   NULL,
   NULL,
   '0',
   '0',
   '1000',
   '2013-5-30 15:02:33',
   '2013-5-30 15:02:33',
   -100,
   'T1',
   'CRM_WS_URL',
   NULL,
   NULL,
   NULL,
   NULL,
   1,
   0,
   31,
   NULL,
   -1,
   -1,
   '0',
   NULL,
   NULL,
   NULL,
   'Y',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   0,
   NULL,
   NULL,
   NULL,
   '',
   NULL,
   NULL,
   NULL,
   '10',
   NULL,
   NULL,
   0,
   0,
   0,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL);

--crm端queryCustOrder服务
INSERT INTO ATTR_VALUE
  (ATTR_VALUE_ID,
   ATTR_VALUE_NAME,
   ATTR_ID,
   ATTR_DESC,
   ATTR_VALUE_TYPE,
   ATTR_FORMAT,
   ATTR_LENGTH,
   ATTR_VALUE,
   MAX_VALUE,
   MIN_VALUE,
   STATUS_DATE,
   CREATE_DATE,
   STATUS_CD,
   PARENT_VALUE_ID,
   ATTR_VALUE_SEQ,
   AREA_ID,
   REGION_CD,
   UPDATE_STAFF,
   CREATE_STAFF,
   REMARK,
   IS_TRANS,
   MANAGE_GRADE,
   EFF_DATE,
   EXP_DATE,
   GROUP_CD,
   UPDATE_DATE)
VALUES
  (-800002000,
   'queryCustOrder',
   -950012806,
   '订单查询',
   NULL,
   NULL,
   NULL,
   '<?xml version="1.0" encoding="UTF-8"?>
<root>
	<msgHead>
		<time>20111230114143</time>
		<from>SRM</from>
		<to>CRM</to>
		<sysSign>SRM</sysSign>
		<msgType>queryCustOrder</msgType>
		<serial>45646405</serial>
	</msgHead>
	<msgBody>
		<outParam>
			<result>0</result>
			<customerOrder>
				<customerOrderId>2222</customerOrderId>
				<custSoNumber>FJ22222</custSoNumber>
				<statusCd>10000</statusCd>
			</customerOrder>
		</outParam>
	</msgBody>
</root>',
   NULL,
   NULL,
   '2012-1-5 12:00:00',
   '2012-1-5 12:00:00',
   '1000',
   NULL,
   NULL,
   2,
   11,
   NULL,
   NULL,
   NULL,
   '0',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL);

--crm端checkPhotoNotReDeal服务
INSERT INTO ATTR_VALUE
  (ATTR_VALUE_ID,
   ATTR_VALUE_NAME,
   ATTR_ID,
   ATTR_DESC,
   ATTR_VALUE_TYPE,
   ATTR_FORMAT,
   ATTR_LENGTH,
   ATTR_VALUE,
   MAX_VALUE,
   MIN_VALUE,
   STATUS_DATE,
   CREATE_DATE,
   STATUS_CD,
   PARENT_VALUE_ID,
   ATTR_VALUE_SEQ,
   AREA_ID,
   REGION_CD,
   UPDATE_STAFF,
   CREATE_STAFF,
   REMARK,
   IS_TRANS,
   MANAGE_GRADE,
   EFF_DATE,
   EXP_DATE,
   GROUP_CD,
   UPDATE_DATE)
VALUES
  (-800002001,
   'checkPhotoNotReDeal',
   -950012806,
   '判断是否是拍照甩单，并且没有关联别的订单或者订单项',
   NULL,
   NULL,
   NULL,
   '<?xml version="1.0" encoding="UTF-8"?>
<root>
	<msgHead>
		<time>20111230114143</time>
		<from>SRM</from>
		<to>CRM</to>
		<sysSign>SRM</sysSign>
		<msgType>checkPhotoNotReDeal</msgType>
		<serial>45646405</serial>
	</msgHead>
	<msgBody>
		<outParam>
			<result>0</result>
			<isPhoto>1</isPhoto>
		</outParam>
	</msgBody>
</root>',
   NULL,
   NULL,
   '2012-1-5 12:00:00',
   '2012-1-5 12:00:00',
   '1000',
   NULL,
   NULL,
   2,
   11,
   NULL,
   NULL,
   NULL,
   '0',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL);

--crm端checkPhotoNotReDeal服务
INSERT INTO ATTR_VALUE
  (ATTR_VALUE_ID,
   ATTR_VALUE_NAME,
   ATTR_ID,
   ATTR_DESC,
   ATTR_VALUE_TYPE,
   ATTR_FORMAT,
   ATTR_LENGTH,
   ATTR_VALUE,
   MAX_VALUE,
   MIN_VALUE,
   STATUS_DATE,
   CREATE_DATE,
   STATUS_CD,
   PARENT_VALUE_ID,
   ATTR_VALUE_SEQ,
   AREA_ID,
   REGION_CD,
   UPDATE_STAFF,
   CREATE_STAFF,
   REMARK,
   IS_TRANS,
   MANAGE_GRADE,
   EFF_DATE,
   EXP_DATE,
   GROUP_CD,
   UPDATE_DATE)
VALUES
  (-800002002,
   'removeCustOrderMap',
   -950012806,
   '移除订单接口映射记录',
   NULL,
   NULL,
   NULL,
   '<?xml version="1.0" encoding="UTF-8"?>
<root>
	<msgHead>
		<time>20111230114143</time>
		<from>SRM</from>
		<to>CRM</to>
		<sysSign>SRM</sysSign>
		<msgType>removeCustOrderMap</msgType>
		<serial>45646405</serial>
	</msgHead>
	<msgBody>
		<outParam>
			<result>0</result>
		</outParam>
	</msgBody>
</root>',
   NULL,
   NULL,
   '2012-1-5 12:00:00',
   '2012-1-5 12:00:00',
   '1000',
   NULL,
   NULL,
   2,
   11,
   NULL,
   NULL,
   NULL,
   '0',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL);

--crm端checkRelIntfDepOrder服务
INSERT INTO ATTR_VALUE
  (ATTR_VALUE_ID,
   ATTR_VALUE_NAME,
   ATTR_ID,
   ATTR_DESC,
   ATTR_VALUE_TYPE,
   ATTR_FORMAT,
   ATTR_LENGTH,
   ATTR_VALUE,
   MAX_VALUE,
   MIN_VALUE,
   STATUS_DATE,
   CREATE_DATE,
   STATUS_CD,
   PARENT_VALUE_ID,
   ATTR_VALUE_SEQ,
   AREA_ID,
   REGION_CD,
   UPDATE_STAFF,
   CREATE_STAFF,
   REMARK,
   IS_TRANS,
   MANAGE_GRADE,
   EFF_DATE,
   EXP_DATE,
   GROUP_CD,
   UPDATE_DATE)
VALUES
  (-800002003,
   'checkRelIntfDepOrder',
   -950012806,
   '判断是否已经有关联Intf_Dep_Order',
   NULL,
   NULL,
   NULL,
   '<?xml version="1.0" encoding="UTF-8"?>
<root>
	<msgHead>
		<time>20111230114143</time>
		<from>SRM</from>
		<to>CRM</to>
		<sysSign>SRM</sysSign>
		<msgType>checkRelIntfDepOrder</msgType>
		<serial>45646405</serial>
	</msgHead>
	<msgBody>
		<outParam>
			<result>0</result>
			<isRel>1</isRel>
		</outParam>
	</msgBody>
</root>',
   NULL,
   NULL,
   '2012-1-5 12:00:00',
   '2012-1-5 12:00:00',
   '1000',
   NULL,
   NULL,
   2,
   11,
   NULL,
   NULL,
   NULL,
   '0',
   NULL,
   NULL,
   NULL,
   NULL,
   NULL);
